### ISSUE TITLE
Generate End Main Island (Suggestion)

### ISSUE THREAD

**Issue by angelapuzzle** [alcatrazEscapee/hexlands#1]
When going to the end there is no pillars, so the ender dragon is easier to defeat, supposing you find the structure where he perches, since in some cases you spawn over the void and it's difficult to find.
It would be neat if it generated properly, it could be like a big group of hexagons where the main island is generated, however I guess it wouldn't be something easy to do.

**Comment by alcatrazEscapee** [comment]
It is very easy to do. In fact, you can do it yourself with a datapack, even just by changing one file. However, I have to get into the *reason* they don't spawn:

- End spikes (pillars) only spawn in "The End" biome.
- "The End" biome only appears in a small radius around the origin of the dimension.
- In all dimensions, Hex Lands shrinks the realitive size or scale of biomes, in order to reduce the number of adjacent hexes with the same biome - as otherwise this looks very boring and not very hexagonal at all.
- The end, in vanilla, has five biomes. And without this scaling effect, it barely looks hexagonal.

So, the root cause of the issue has this as an (un)intentional side effect. The end has a rather unique biome setup, and I'm not convinced I should preserve that in Hex Lands.

**Comment by angelapuzzle** [comment]
In the case of wanting to do it with a datapack (which I surely want to do) or changing that file, how do I make that datapack or what file I need to change?

**Comment by alcatrazEscapee** [comment]
Two ways:

1. Override the End dimension, exactly as described in the [relavant readme section](https://github.com/alcatrazEscapee/hexlands#data-packs), except change the `biome_scale` value to 1 (or another smaller value than the default (4) which gives enough space for the end pillars to spawn). This will have the aforementioned effects on overall biome placement in the End.
2. Add the end spikes feature to other end biomes (not just "the end", but also any end biomes that may spawn nearby - including all the vanilla end biomes, but also any modded end biomes you've added.). This one gets tricky as you have to override the entire biome to add the feature (it's rather inconvenient like that)
