### ISSUE TITLE
Tag fails to load, resulting in config not working.

### ISSUE THREAD

**Issue by murphyneko** [alcatrazEscapee/hexlands#13]
I am running Hexlands 4.0.0 on 1.19.2. On launch I get the following error:
`[31Oct2023 23:05:33.424] [Worker-Main-19/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [hexlands:hexlands (from hexlands-forge-1.19.2-4.0.0.jar), hexlands:hexlands_overworld_only (from hexlands-forge-1.19.2-4.0.0.jar), gardenofglass:gardenofglass (from gardenofglass-1.11.jar)] as it is missing following references: hexlands:hexlands (from hexlands-forge-1.19.2-4.0.0.jar), 
	hexlands:hexlands_overworld_only (from hexlands-forge-1.19.2-4.0.0.jar), 
	gardenofglass:gardenofglass (from gardenofglass-1.11.jar)
[31Oct2023 23:05:33.424] [Worker-Main-19/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecraft:normal (from Default)] as it is missing following references: #minecraft:normal (from Default)`

As a result, Hexlands completely ignores the datapack worlgen file.

This is file .minecraft/kubejs/data/minecraft/dimension/overworld.json :
```java
{
	"type": "minecraft:overworld",
	"generator": {
		"type": "hexlands:hexlands",
		"seed": 0,
		"settings": "minecraft:overworld",
		"hex_settings": {
			"biome_scale": 8,
			"hex_size": 40,
			"hex_border_threshold": 0.95,
			"bottom_border": {
				"min_height": 62,
				"max_height": 65,
				"state": {
					"Name": "nyagibits_bytes:flake",
					"Properties": {}
				}
			}
		},
		"biome_source": {
			"type": "multi_noise",
			"preset": "overworld"
		},
		"forge:use_server_seed": false
	}
}
``` 
How do I fix this?

**Comment by alcatrazEscapee** [comment]
Tag failing to load is typically caused by one of the elements failing to load, probably an error in your datapack somewhere. In either case, I am not supporting 1.19 anymore so good luck.

**Comment by DeepwaterCreations** [comment]
I'm not sure it's something unique to their datapack - I get the same error in a fresh, vanilla 1.19.2 Minecraft with only hexlands-forge-1.19.2-4.0.0 and no other mods:

`[17:15:12] [Worker-Main-7/ERROR] [minecraft/TagLoader]: Couldn't load tag [hexlands:hexlands (from hexlands-forge-1.19.2-4.0.0.jar), hexlands:hexlands_overworld_only (from hexlands-forge-1.19.2-4.0.0.jar)] as it is missing following references: hexlands:hexlands (from hexlands-forge-1.19.2-4.0.0.jar), 
	hexlands:hexlands_overworld_only (from hexlands-forge-1.19.2-4.0.0.jar)
[17:15:12] [Worker-Main-7/ERROR] [minecraft/TagLoader]: Couldn't load tag [#minecraft:normal (from Default)] as it is missing following references: #minecraft:normal (from Default)`

In that case, it still works, but in my in-progress mod that uses hexland as a dependency, datapack validation fails for everything. I also get this error:

`Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: hexlands:hexlands missed input: {"minecraft:overworld":{"type":"minecraft:overworld","generator":{"type":"hexlands:hexlands","settings":"minecraft:overworld","biome_source":{"type":"minecraft:multi_noise","preset":"minecraft:overworld"},"hex_settings":"hexlands:overworld"}}}; Missing overworld dimension`

Could be that one's my fault somehow, but there's barely anything going on in my mod yet, and the resources/data folder is empty.

Anyway, I get that you're not supporting 1.19, but if you have any insight at all into this, it'd be appreciated! I'm happy to do a PR for you if there's a fix I can implement.
