### ISSUE TITLE
Suggestion: world type that uses all available biomes, ignoring dimension.

### ISSUE THREAD

**Issue by NixityNull** [alcatrazEscapee/hexlands#19]
I was hoping to make a modpack involving the concept of dimensions breaking/crossover nonsense and I was hoping for the world generation to be entirely random, including biomes from other dimensions. All of the current options seem to only create hexagons of local biomes in their home dimension.

Creating a single biome world using biomes from other dimensions in the overworld proves that the overworld can generate biomes from other dimensions, I would be interested in possibly customizing this to happen at random using the hexlands style of generation. Hell, I'd even settle for a separate mod that does it without hexagonal generation.

**Comment by alcatrazEscapee** [comment]
This is something you could already do with existing biome sources provided by mojang, either with the checkerboard or multinoise biome source. The hexlands chunk generator allows you to supply your own biome source for this reason.

**Comment by NixityNull** [comment]
Well it would be nice if you could explain what any of that means before you completely dismiss me.

**Comment by ParasiticSquid** [comment]
I agree with NixityNull, why not do a step by step explanation so the average player actually knows how they can do that instead of just going "You already can, bye."

Or you can, you know, add actual config files instead of just assuming everyone knows how to use datapacks? I miss the old days where modders actually cared about configurability and compatibility with other mods built in by default instead getting lazy and just telling people to make a datapack themselves as if this knowledge is known by everyone. Spoiler alert: Almost no one but professional modpack makers who have been doing it for years( and even then kubejs is superior in many ways to datapacks for certain modpacks ) and modders actually know how to make datapacks.

So no. We normal players can't add new biomes or configure things because of a critical lack of config files to actually do that without having to learn how to code from scratch, which 90% of players won't do for obvious reasons. Simple as that.
