### ISSUE TITLE
Feature Request: Height Adjustment

### ISSUE THREAD

**Issue by Darkosto** [alcatrazEscapee/hexlands#3]
Hello!

Firstly, I would like to thank you for updating this mod into 1.16! I'm happy that it hasn't been lost.

I do have a request for you, or maybe you can point me in the right direction: Back when I was setting up a pack with Hexlands in 1.12, there was an option to adjust biome heights so the hex tiles were flatter or taller depending on how you set it up. I've included this image to describe it a bit better. Is this something you can help with?

Thank you so much!
Darkosto

![2021-11-18_13 44 13](https://user-images.githubusercontent.com/10309699/142501725-a03937a9-3f9c-4c4f-9913-03d772eb6eff.png)

**Comment by alcatrazEscapee** [comment]
Hmmm.

So this should be already doable with a world generation datapack, but it's not easy. Here's the idea:

- Hexlands just generates terrain from the biome itself within the hexes, using vanilla's noise generation settings. In particular, this includes the depth and scale settings from each biome.
- Depth and scale control both the overall height of the biome (depth), and how much vertical variation there is (scale). From the [Minecraft wiki article](https://minecraft.fandom.com/wiki/Biome/JSON_format):
  - `depth`: Used for terrain noise generation. Biomes with positive depth are considered land, biomes with negative depth are oceans.
   - `scale`: Used for terrain noise generation. Vertically stretches the terrain. Lower values produce flatter terrain.

So, flatter biomes (or the opposite) can be achieved by modifying the `scale` parameter of individual biomes, for flatness on a per-biome level. Which involves replacing the entire biome in a world generation datapack (this is the "doable, yet not easy" part).

---

(If it's desirable to have this configurability exposed in a simpler fashion by Hex Lands itself a. la. #1, it is much easier to implement this with a mod than with a datapack due to vanilla's format limitations)

**Comment by Darkosto** [comment]
I've been working on getting this setup via datapacks and so far I notice a difference. It's not quite as flat as I was hoping, but it is much better:

![2021-11-19_15 35 51](https://user-images.githubusercontent.com/10309699/142704197-6c76922d-ad85-4fb2-8323-26a46161873b.png)

I don't mind using this small height difference, but is it possible to lower the hex border at all? I've noticed the border will come up and over the hex terrain more often than not. 

Thanks again for your help!

**Comment by alcatrazEscapee** [comment]
The border is calculated as an average of the biome's height, assuming zero influence from noise, and then it's randomly (but uniformly) varied on a per-hex basis. So changing the depth and scale will influence the border as well.

However, due to the impreciseness of calculating the average biome height (as it's literally an assumption of no overworld terrain noise) and making a best guess at the terrain height, it's not terribly accurate (although it should be uniformly distributed about the average biome height in any case).

So outside of modifying depth or scale, there is nothing that can be done as yet. If there's a more specific adjustment you were thinking of (i.e. besides the existing `no_border`, `windowed_border`, etc. options) I could look into that as an option.

**Comment by alcatrazEscapee** [comment]
With vanilla adding density functions, controlling the height of hexes should be as explicit as possible (the height could be set arbitrarily and precisely flat), and the border settings in 1.18 are uniform (as predicting average height with density functions is nontrivially difficult), which can also be exactly specificied.

In short, in 1.18 it should be possible to get superflat style hexes, and hex borders, if that is your desire.
